import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#091413',
  '--slot4-page-text': '#e8f5ef',
  '--slot4-panel-bg': '#10201d',
  '--slot4-surface-bg': '#122723',
  '--slot4-muted-text': '#9db9ae',
  '--slot4-soft-muted-text': '#6f8f83',
  '--slot4-accent': '#408A71',
  '--slot4-accent-fill': '#408A71',
  '--slot4-accent-soft': 'rgba(176, 228, 204, 0.14)',
  '--slot4-on-accent': '#091413',
  '--slot4-dark-bg': '#06100f',
  '--slot4-dark-text': '#ecf8f2',
  '--slot4-media-bg': '#18312b',
  '--slot4-cream': '#eff9f4',
  '--slot4-warm': '#0d1917',
  '--slot4-lavender': '#0f1d1a',
  '--slot4-gray': '#142421',
  '--slot4-body-gradient': 'radial-gradient(circle at top, rgba(64,138,113,0.16), transparent 34%), linear-gradient(180deg, #0b1514 0%, #091413 38%, #071110 100%)',
  '--editable-page-bg': '#091413',
  '--editable-page-text': '#e8f5ef',
  '--editable-container': '1440px',
  '--editable-border': 'rgba(176, 228, 204, 0.15)',
  '--editable-nav-bg': 'rgba(9, 20, 19, 0.86)',
  '--editable-nav-text': '#edf9f4',
  '--editable-nav-active': '#B0E4CC',
  '--editable-nav-active-text': '#091413',
  '--editable-cta-bg': '#B0E4CC',
  '--editable-cta-text': '#091413',
  '--editable-search-bg': 'rgba(255,255,255,0.06)',
  '--editable-footer-bg': '#07100f',
  '--editable-footer-text': '#dbefe5',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-cream)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_45px_rgba(0,0,0,0.16)]',
  shadowStrong: 'shadow-[0_28px_70px_rgba(0,0,0,0.26)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(3,10,9,0.08),rgba(3,10,9,0.84))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[86rem] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[1.12fr_0.88fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[210px] shrink-0 snap-start sm:w-[240px]',
  },
  type: {
    eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-semibold leading-[1.03] tracking-[-0.05em] sm:text-5xl lg:text-[4.5rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.04em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.75rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-white/5 px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-cream)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.5rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/5]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_50px_rgba(0,0,0,0.25)] motion-reduce:hover:translate-y-0',
    fade: 'transition duration-300 hover:opacity-88',
  },
} as const

export const aiLayoutRules = [
  'Lead with the evergreen palette and dark gallery canvas defined in editableRootStyle.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use varied card silhouettes across hero, rails, list sections, and detail-related content.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
